# Generated by Django 2.2.11 on 2020-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200401_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=20)),
                ('password', models.CharField(help_text='密码', max_length=32)),
                ('sex', models.IntegerField(blank=True, choices=[('0', '男'), ('1', '女')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
